Medicine and Health: 0.3
Computer Science and Technology: 0.3
Economics and Finance: 0.3
Education and Training: 0.3
Engineering: 0.3
Environmental Science and Energy: 0.3
Arts and Design: 0.7
Entertainment and Media: 0.4
Law and Politics: 0.0
Mathematics and Statistics: 0.0
Physics: 0.0
Chemistry: 0.0
Biology: 0.0
Psychology: 0.3
Philosophy and Ethics: 0.5
Sociology and Anthropology: 0.5
History: 0.0
Literature and Linguistics: 0.7
Sports and Exercise Science: 0.5
Tourism and Hotel Management: 0.3